### ISSUE TITLE
Fix console error for sign up page

### ISSUE THREAD

**Issue by mirrorkeydev** [googleinterns/noms#35]
![image](https://user-images.githubusercontent.com/35010111/89206854-b5b6db00-d56e-11ea-89f3-dd6a27281ca9.png)

This error doesn't occur on any of the other pages for me, so I'm not sure what's up :0

**Comment by areetaw** [comment]
I just pulled from master and I can't seem to get the same console errors! Do you mind checking if this error still occurs?

**Comment by mirrorkeydev** [comment]
Doesn't seem to be happening on my local version anymore either! You can check out the error in the deployed version, but we must have inadvertently fixed it between that deploy and now :)
