### ISSUE TITLE
Get 25+ Googlers to Test Our Application

### ISSUE THREAD

**Issue by areetaw** [googleinterns/noms#47]
In order to continuously improve our application, we will implement user research through a Google form: go/nomsappfeedback. By the end of the internship, we will get at least 25 Googlers to go through our application and test

- Usability 
- Accessibility
- Interest

**Comment by mirrorkeydev** [comment]
Combined responses from the general user feedback form and the bug bash indicate we have tested our application on 20 Googlers so far!

**Comment by areetaw** [comment]
After deploying our most recent version of the application and sending out the feedback form again, we've reached our goal and will be creating issues related to the feedback!
