### ISSUE TITLE
Track and Report Metrics

### ISSUE THREAD

**Issue by areetaw** [googleinterns/noms#48]
After we're complete with all features, we can find statistics that demonstrate the highlights of our project!

**Comment by mirrorkeydev** [comment]
Metric impact for adding the autocomplete dropdown is discussed in #62

**Comment by areeta** [comment]
Test Metrics:
![image](https://user-images.githubusercontent.com/20546538/92183980-b7d9b700-ee04-11ea-9a40-86c58059b211.png)

Adding a User to Datastore: 0.2248 seconds
Adding a Post to Datastore: 0.035 seconds
Sending an email to users for a new post: 0.235 seconds
