### ISSUE TITLE
Make Users Pick Our Supported Colleges

### ISSUE THREAD

**Issue by areetaw** [googleinterns/noms#81]
Users are able to put in gibberish for colleges 

![image](https://user-images.githubusercontent.com/20546538/90572914-07b05100-e16a-11ea-8e20-6fb35084d91f.png)

**Comment by mirrorkeydev** [comment]
Saw you opened this, I also ran into a similar issue on the homepage! If it's helpful, here's how I solved it:
https://github.com/googleinterns/noms/blob/afa936c0c86aadaf7af7f31214942b9bc7307a72/src/main/webapp/assets/js/indexScript.js#L182-L196

**Comment by areetaw** [comment]
> Saw you opened this, I also ran into a similar issue on the homepage! If it's helpful, here's how I solved it:
> https://github.com/googleinterns/noms/blob/afa936c0c86aadaf7af7f31214942b9bc7307a72/src/main/webapp/assets/js/indexScript.js#L182-L196
> 
> 
> It aborts navigation if the option picked is not in the list, forcing the user to backspace and pick a dropdown option :)

Yes, I saw that; thank you for sending this over! However, with the sign up form, it'll trigger with or without the college exiting in the list because the submit aspect is attached to the HTML form that triggers a POST request when the form is submitted. Therefore, I need to take out the POST from the HTML and create the submit on the JavaScript side!
