### ISSUE TITLE
Handling Submissions Without Images Attached

### ISSUE THREAD

**Issue by ubahl** [googleinterns/noms#97]
For the "upload photo" feature on the create post modal, there are a couple routes we could go.

**Make uploading a file mandatory**
Pros:
-  All the posts will have a photo
- A more uniform look to the site

Cons:
- More effort on user's end to submit a post
- Users might be posting from a laptop, making taking a photo harder

**Making uploading a file optional**
Pros:
- People who want to upload a photo are able to
- Allows for more flexibility on the user's end

Cons:
- Posts are less uniform

I personally think **optional** would be a better route to go. However, if we go this route, this leads to the question of how to present posts without an image. This leads to two options:

![Screenshot 2020-08-27 at 10 32 45 AM](https://user-images.githubusercontent.com/48428336/91476162-71f38080-e851-11ea-8dd3-987ffd7a3380.png)

**Using a stock image to fill the image spot**
Pros:
- All posts will have an image
- A more uniform look to the posts

Cons:
- Users may be confused by this stock image
- Adds unnecessary information to the page

**Omitting the image**
Pros:
- Does not present a random image
- Less confusion among the users

Cons:
- Cards look less uniform

I think it might be best to omit the image and have a mix between posts with and without images, but I would love to hear your opinions!

**Comment by mrboxtobox** [comment]
Optional with a nice-looking stock SGTM (could have a few to vary things up)

**Comment by mirrorkeydev** [comment]
I agree that posting a photo should be **optional**, and that the consistency of using a stock image is a benefit! :)

This is a really out-there idea, but it would be cool if we could use the 'food type' of the post in order to query a stock image and then use that image for the post! However, this would be pretty complex to implement.

Therefore, my vote is for **optional, but use a stock image to fill non-picture posts**

**Comment by areetaw** [comment]
I also agree that posting a photo should be **optional** since not everyone has the time or a photo to put! My vote is also for **optional, but use a stock image to fill non-picture posts**!
